apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-gateway
  name: udagram-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-gateway
  template:
    metadata:
      labels:
        service: udagram-api-gateway
    spec:
      containers:
      - image: nowindi/udagram-api-gateway
        name: udagram-api-gateway
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


