apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-gateway
  name: udagram-api-gateway-svc
spec:
  ports:
  - name: "udagram-api-gateway"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-api-gateway
